### PR TITLE
Remove core folder and merge missing files

### PR DESCRIPTION
**Pull request by enioluwa23**
Gets rid of the duplication of the back-end code. Scrutinize this PR for any missing content.

### CODE REVIEW

**Comment by ryanhassing** [comment]
Looks like we still have a `package-lock.json` duplicate. One in `chariot` and one in `chariot/gui`. @jh3377 which of these should be removed?

**Comment by jh3377** [comment]
Mentioned this in the other thread, but the one in gui could be removed

**Comment by ryanhassing** [comment]
I see no other issues. Approving.

**Comment by enioluwa23** [comment]
Closes #31

**Pull request merged**
